name: releaser
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .github/**
      - '!.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout for Github repository workspace
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set path env to lower case
        id: lower-case
        run: echo "REGISTRY_PATH=${var,,}" >> "$GITHUB_OUTPUT"
        env:
          # github.repository as <account>/<repo>
          var: ghcr.io/${{ github.repository }}

      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x
          push: true
          tags: ${{ steps.lower-case.outputs.REGISTRY_PATH }}:latest
